version: 2

models:
  - name: fct_orders
    description: >
      This fact table (`fct_orders`) provides a comprehensive view of all customer orders.
      It aggregates order-level details and links to relevant dimensions like customers,
      employees, and stores. This model is crucial for analyzing sales performance,
      customer behavior, and operational efficiency.
    columns:
      - name: order_id
        description: >
          The unique identifier for each order. This serves as the primary key for this
          fact table and is used to join with other related tables.
        tests:
          - unique
          - not_null
      - name: customer_id
        description: >
          The foreign key linking to the `stg_customers` table, representing the customer
          who placed the order. This allows for analysis of orders by customer demographics.
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_date
        description: >
          The date on which the order was placed. This column is essential for time-series
          analysis of sales and order trends.
        tests:
          - not_null
      - name: revenue
        description: >
          The total revenue generated by this specific order, calculated from the sum of
          all line items. This is a key metric for sales performance.
        tests:
          - not_null
          - dbt_utils.at_least_one

  - name: customer_revenue
    description: >
      This aggregated model (`customer_revenue`) calculates the total revenue generated
      by each customer. It provides a high-level view of customer value and is used
      for customer segmentation and marketing analysis.
    columns:
      - name: customer_id
        description: >
          The unique identifier for each customer, serving as the primary key for this
          aggregated table.
        tests:
          - unique
          - not_null
      - name: total_revenue
        description: >
          The sum of all revenue generated by a specific customer across all their orders.
          This metric helps identify high-value customers.
        tests:
          - not_null
          - dbt_utils.at_least_one

  - name: fct_customer_segmentation
    description: >
      This fact table (`fct_customer_segmentation`) assigns customers to specific segments
      (e.g., 'Regular', 'New') based on predefined criteria. This model is used for
      targeted marketing campaigns and personalized customer experiences.
    columns:
      - name: customer_id
        description: >
          The unique identifier for each customer, serving as the primary key for this
          segmentation table.
        tests:
          - unique
          - not_null
      - name: segment_name
        description: >
          The assigned segment name for the customer. Possible values include 'Regular'
          and 'New', indicating different customer behaviors or lifecycle stages.
        tests:
          - accepted_values:
              values: ['Regular', 'New']

  - name: fct_store_performance
    description: >
      This fact table (`fct_store_performance`) provides key performance indicators
      for each store, focusing on revenue. It helps in evaluating the performance
      of individual retail locations.
    columns:
      - name: store_name
        description: >
          The name of the store, serving as a unique identifier for each retail location.
          This is the primary key for this performance table.
        tests:
          - unique
          - not_null
      - name: actual_revenue
        description: >
          The actual total revenue generated by the store. This metric is crucial for
          assessing store profitability and identifying top-performing locations.
        tests:
          - not_null
          - dbt_utils.at_least_one